version: "3"
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres@db/postgres"
    ports:
      - "8080:8080"
    links:
      - db
    volumes:
      - .:/app:ro